# Generated by Django 5.1.5 on 2025-04-06 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendamento_lembrete_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancel_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
