# Generated by Django 5.1.5 on 2025-04-06 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_agendamento_cancel_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
