# Generated by Django 5.2 on 2025-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_bloqueiosemanalpadrao_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do cancelamento'),
        ),
    ]
