# Generated by Django 5.2 on 2025-05-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0017_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(default='aguardando_inicio', max_length=50)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.barbeiro')),
            ],
        ),
    ]
