# Generated by Django 5.1.5 on 2025-04-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_agendamento_lembrete_minutos_agendamento_servico'),
        ('botwhatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacliente',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.barbeiro'),
        ),
    ]
